#!/usr/bin/env bash
# Pre-flight: prove nothing in the download manifest is already on disk or in the
# warm archive, and that no job currently owns the paths we are about to write.
#
# This exists because a 3.4 GB Wang FASTQ re-download happened on 2026-08-24 from
# an availability survey that used `find -maxdepth 1` and missed files at depth 3.
# Every find below is FULL DEPTH, no depth cap.
#
# Usage: bash scripts/xspecies/preflight_survey.sh
# Writes docs/XSPECIES_PREFLIGHT.md and exits nonzero if anything needs a decision.
set -uo pipefail

NEW=/private/groups/carpenterlab/emalekos/RNAZoo_meta/RNAZoo/experiments/riboseq_signal_model
PROJ=/private/groups/carpenterlab/emalekos/RNAZoo_meta
ARCHIVE=/private/warm-archive/carpenterlab/RNAZoo_meta
MANIFEST="$NEW/data/external/xspecies/download_manifest.tsv"
OUT="$NEW/docs/XSPECIES_PREFLIGHT.md"
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT

[ -s "$MANIFEST" ] || { echo "missing $MANIFEST; run select_runs.py first" >&2; exit 2; }

accs=$(awk -F'\t' 'NR>1{print $6}' "$MANIFEST" | sort -u)
n_acc=$(wc -l <<< "$accs")
issues=0

{
  echo "# Cross-species ingest pre-flight ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
  echo
  echo "Generated by \`scripts/xspecies/preflight_survey.sh\`. Manifest:"
  echo "\`data/external/xspecies/download_manifest.tsv\`, **$n_acc accessions**."
  echo
  echo '## 1. Local presence, FULL DEPTH'
  echo
} > "$OUT"

# One find over the whole data tree, then match accessions against it. Far cheaper
# than N finds, and it cannot accidentally acquire a depth cap.
find "$NEW/data" "$NEW/proteogenomics" -type f 2>/dev/null > "$TMP/alltree.txt"
echo "  indexed $(wc -l < "$TMP/alltree.txt") files under data/ and proteogenomics/" >&2

: > "$TMP/hits.txt"
while read -r a; do
  [ -z "$a" ] && continue
  if grep -F "$a" "$TMP/alltree.txt" > "$TMP/one.txt"; then
    fq=$(grep -cE '\.(fastq|fq)(\.gz)?$' "$TMP/one.txt")
    other=$(( $(wc -l < "$TMP/one.txt") - fq ))
    printf '%s\t%s\t%s\t%s\n' "$a" "$fq" "$other" "$(head -1 "$TMP/one.txt")" >> "$TMP/hits.txt"
  fi
done <<< "$accs"

if [ -s "$TMP/hits.txt" ]; then
  echo "| accession | local FASTQ | other local files | example path |" >> "$OUT"
  echo "|---|---|---|---|" >> "$OUT"
  while IFS=$'\t' read -r a fq other ex; do
    echo "| \`$a\` | **$fq** | $other | \`${ex#$NEW/}\` |" >> "$OUT"
  done < "$TMP/hits.txt"
  nfq=$(awk -F'\t' '$2>0' "$TMP/hits.txt" | wc -l)
  echo >> "$OUT"
  if [ "$nfq" -gt 0 ]; then
    echo "**$nfq accessions already have FASTQ on disk.** Do not re-fetch these; verify md5 and reuse." >> "$OUT"
    issues=1
  else
    echo "No manifest accession has a local FASTQ. Accessions appearing above exist only as" >> "$OUT"
    echo "downstream products (BAM, P-sites), which is why they are being re-fetched." >> "$OUT"
  fi
else
  echo "No manifest accession appears anywhere under \`data/\` or \`proteogenomics/\`." >> "$OUT"
fi

{
  echo
  echo '## 2. Warm archive'
  echo
} >> "$OUT"
if [ -r "$NEW/data/ARCHIVE_INDEX.tsv" ]; then
  hit=$(grep -Ff <(echo "$accs") "$NEW/data/ARCHIVE_INDEX.tsv" 2>/dev/null | wc -l)
  echo "\`data/ARCHIVE_INDEX.tsv\`: $(( $(wc -l < "$NEW/data/ARCHIVE_INDEX.tsv") - 1 )) rows, **$hit** mention a manifest accession." >> "$OUT"
  [ "$hit" -gt 0 ] && issues=1
else
  echo "\`data/ARCHIVE_INDEX.tsv\` not readable." >> "$OUT"; issues=1
fi
echo >> "$OUT"
echo "\`*.ARCHIVED.md\` stubs (depth-capped: stubs are left beside the data they replace," >> "$OUT"
echo "which is always under \`data/\`; an uncapped find over the 5.7 TB project tree takes" >> "$OUT"
echo "tens of minutes on ceph and finds nothing extra):" >> "$OUT"
echo >> "$OUT"
find "$NEW/data" -maxdepth 3 -name '*.ARCHIVED.md' 2>/dev/null | sed "s|$NEW/|- \`|;s|$|\`|" >> "$OUT"
# A direct look at the archive tree, in case a path was archived without indexing.
# Capped at 3 levels: the archive mirrors the project tree, so an accession-named
# directory would appear near the top, and a 6-level walk of 5.3 TB is not worth it.
echo >> "$OUT"
if [ -d "$ARCHIVE" ]; then
  arch_hit=$(timeout 120 find "$ARCHIVE" -maxdepth 4 -type d 2>/dev/null | grep -Ff <(echo "$accs") | wc -l)
  echo "Direct scan of \`$ARCHIVE\` (4 levels): **$arch_hit** directories name a manifest accession." >> "$OUT"
  [ "$arch_hit" -gt 0 ] && issues=1
else
  echo "Warm archive not mounted at \`$ARCHIVE\`." >> "$OUT"; issues=1
fi

{
  echo
  echo '## 3. Nothing else owns these paths'
  echo
  echo '```'
  echo "squeue -u $USER:"
  squeue -u "$USER" -o '%.10i %.30j %.9P %.8T %.10M %R' 2>&1 | head -20
  echo
  echo "live PID files in /tmp:"
  for f in /tmp/fetch_*_pid.txt; do
    [ -e "$f" ] || continue
    p=$(cat "$f" 2>/dev/null)
    if kill -0 "$p" 2>/dev/null; then echo "  $f -> $p ALIVE"; else echo "  $f -> $p dead"; fi
  done
  echo '```'
  echo
  echo '## 4. Disk'
  echo
  echo '```'
  used=$(getfattr -n ceph.dir.rbytes --only-values /private/groups/carpenterlab 2>/dev/null)
  echo "$used" | awk '{printf "group ceph used: %.2f TB decimal (%.2f TiB) of a 15 TB quota -> %.2f TB free\n", $1/1e12, $1/1099511627776, 15-$1/1e12}'
  df -h /private/warm-archive | tail -1 | awk '{printf "warm archive: %s size, %s used, %s avail\n",$2,$3,$4}'
  echo '```'
  echo
  echo '## 5. Manifest totals'
  echo
  echo '```'
  awk -F'\t' 'NR>1{n[$2"\t"$3]++; g[$2"\t"$3]+=$13; tot+=$13}
    END{for(k in n) printf "%-22s %3d runs %8.1f GiB\n", k, n[k], g[k];
        printf "%-22s %3d runs %8.1f GiB\n","TOTAL",NR-1,tot}' "$MANIFEST" | sort
  echo '```'
} >> "$OUT"

echo >> "$OUT"
if [ "$issues" -eq 0 ]; then
  echo '**Pre-flight clean: nothing in the manifest exists locally or in the archive.**' >> "$OUT"
else
  echo '**Pre-flight raised at least one item above that needs a decision before fetching.**' >> "$OUT"
fi

echo "wrote $OUT (issues=$issues)"
exit "$issues"
